name: "Setup the project"
runs:
  using: "composite"
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "16.x"
        cache: "yarn"
    - name: Install packages
      run: yarn install
      shell: bash
    - name: Build shared directory
      working-directory: ./shared
      run: yarn package
      shell: bash
