name: test and deploy prod
on:
  push:
    branches:
      - main
jobs:
  test:
    uses: ./.github/workflows/test.yml

  deploy:
    needs: [test]
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
