name: test
on:
  workflow_call:
  push:
    # Don't run this workflow twice for these branches
    # (deploy workflows will call this workflow manually)
    branches-ignore:
      - main
jobs:
  jest_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Run jest tests
        run: yarn test:ci

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Lint shared directory
        working-directory: ./shared
        run: |
          yarn type
          yarn lint
          yarn dependency
      - name: Lint backend
        working-directory: ./backend
        run: |
          yarn type
          yarn lint
          yarn dependency
      - name: Lint frontend
        working-directory: ./frontend
        run: |
          yarn type
          yarn lint
          yarn dependency
